version: '3.6'
networks:
  default_bridge:
    external: true
services:
  flame:
    networks: 
      - default_bridge
    image: ghcr.io/fdarveau/flame:latest-multiarch
    container_name: flame
    volumes:
      - /volume1/docker/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005
    environment:
      - PASSWORD=CarbonGTI#2015
    restart: unless-stopped
