networks:
  default_bridge:
    external: true
services:
  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    volumes:
      - /volume1/docker/openwakeword/data:/data
    networks: 
      - default_bridge
    command: --preload-model 'ok_nabu'
    restart: unless-stopped
    ports:
      - 10400:10400
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    volumes:
      - /volume1/docker/whisper/data:/data
    environment:
      - TZ=America/New_York
    command: --model tiny-int8 --language en
    restart: unless-stopped
    networks: 
      - default_bridge
    ports:
      - 10300:10300
  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice en_US-lessac-medium
    volumes:
      - /volume1/docker/piper/data:/data
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    networks: 
      - default_bridge
    ports:
      - 10200:10200
  musicassistant:
    image: ghcr.io/music-assistant/server:latest # <<< Desired release version here (or use beta to get the latest beta version)
    container_name: musicassistant
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - /volume1/docker/musicassistant/data:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info
  snapcast:
    container_name: snapcast
    image: docker.io/sweisgerber/snapcast:latest
    hostname: snapcast
    networks: 
      - default_bridge
    environment:
      - PUID=1026
      - PGID=101
      - TZ=America/New_York
      - START_SNAPCLIENT=false # set to `true` for snapclient to start
      - sampleformat=44100:16:2
      - buffer=333
      # --host: name or ip of compose service or dockerhost
      # --soundcard: <ID> from `snapclient -l` from inside the container
      # - SNAPCLIENT_OPTS=--host snapcast --soundcard <ID>
      #   => Don't use quotes for SNAPCLIENT_OPTS="" !
      # - HOST_AUDIO_GROUP=<AUDIO-GID> # set to GID of host audio group
    restart: "unless-stopped"
    ports:
      - 1704:1704 # port for the actual audio streaming
      - 1705:1705 # port for TCP Json RPC
      - 1780:1780 # port for the SnapWeb Webinterface
    # devices:
      # - /dev/snd:/dev/snd # optional, only if you want to use snapclient
    volumes:
      - /volume1/docker/snapcast/config/:/config/
      - /volume1/docker/snapcast/data/:/data/
      # /audio should get used to place FIFOs for audio playback from mpd/mopidy/host/etc
      - /volume1/docker/snapcast/audio/:/audio/
