networks:
  default_bridge:
    external: true
services:
  uptimekuma:
    networks: 
      - default_bridge
    image: louislam/uptime-kuma
    container_name: Uptime-Kuma
    hostname: uptimekuma
    mem_limit: 4g
    cpu_shares: 1024
    ports:
      - 3444:3001
    volumes:
      - /volume1/docker/uptimekuma:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Americas/New_York
    restart: on-failure:5